// filepath: c:\micro project\campus-exchange\app\layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // All tags on a single line to prevent whitespace text nodes
  return <html lang="en"><head /><body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}>{children}</body></html>;
}
